# NumPy 공부



---



## NumPy 특징

* Numerical Python의 약자
* 고성능 과학 계산용 패키지로 강력한 N차원 배열 객체
* 범용적 데이터 처리에 사용 가능한 다차원 컨테이너
* 정교한 브로드캐스팅(broadcasting) 기능
* 파이썬의 자료형 list와 비슷하지만, 더 빠르고 메모리를 효율적으로 관리
* 반복문 없이 데이터 배열에 대한 처리를 지원하여 빠르고 편리
* 데이터 과학 도구에 대한 생태계의 핵심을 이루고 있음

In [1]:
import numpy as np
np.__version__

'1.24.3'



---



## 배열 생성

### 리스트로 배열 만들기


In [2]:
# 1차원 배열
a1 = np.array([1,2,3,4,5]) 
print(a1)
print(type(a1))
print(a1.shape) # 배열이 어떤 모양을 가지는지 알려주는 속성 shape이다. #쉼표 뒤에 아무것도 없으면 1차원 배열이다.
print(a1[0],a1[1],a1[2],a1[3],a1[4])



[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3 4 5


In [3]:
# 파이썬 리스트와 마찬가지로 수정이 가능하다.
a1[0] = 6
a1[3] =3
print(a1)

[6 2 3 3 5]


In [4]:
# 2차원 배열

a2 = np.array([[1,2,3],
               [4,5,6],
              [7,8,9]])
print(a2)
print(a2.shape) # 3 by 3 짜리 배열이어야 한다. 
print(a2[0,0], a2[1,1], a2[2,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 5 8


In [5]:
# 3차원 배열

a3 = np.array([
    [[1,2,3],[5,6,7],[43,5,65]],
    [[1,3,0],[50,65,7],[3,5,65]],
    [[1,203,3],[556,6,7],[4,556,615]],
              ])
print(a3)
print(a3.shape)

[[[  1   2   3]
  [  5   6   7]
  [ 43   5  65]]

 [[  1   3   0]
  [ 50  65   7]
  [  3   5  65]]

 [[  1 203   3]
  [556   6   7]
  [  4 556 615]]]
(3, 3, 3)


### 배열 생성 및 초기화

* `zeros()`: 모든 요소를 0으로 초기화

In [6]:
np.zeros(13) # 1차원 배열로 13개의 요소를 0으로 초기화함.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

* `ones()`: 모든 요소를 1로 초기화

In [7]:
np.ones((5,5)) # 2차원 배열로 모든 요소를 1로 초기화

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

* `full()`: 모든 요소를 지정한 값으로 초기화

In [8]:
a = np.full((3,3),1.3) # np.full(차원,지정 값)
b = np.full(4,334)
print(a) # a = 2차원
print(b) # b = 1차원

[[1.3 1.3 1.3]
 [1.3 1.3 1.3]
 [1.3 1.3 1.3]]
[334 334 334 334]


* `eye()`: 단위행렬(identity matrix) 생성
  + 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 **정사각 행렬**

In [9]:
np.eye(4) # shape 필요없이 n값만 주면 된다.

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

* `tri()`: 삼각행렬 생성

In [10]:
np.tri(3) # 이거도 마찬가지로 n값만 주면 된다.

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

* `empty()`: 초기화되지 않은 배열 생성
  + 초기화가 없어서 배열 생성비용 저렴하고 빠름
  + 초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있음

In [11]:
np.empty(10) 


array([nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

* `_like()`: 지정된 배열과 shape가 같은 행렬 생성
  + `np.zeros_like()`
  + `np.ones_like()`
  + `np.full_like()`
  + `np.empty_like()`

In [12]:
print(a1)
np.zeros_like(a1) # a1의 shape과 같은 모양으로 0이 채워진 배열을 만들어주라는 의미이다.

[6 2 3 3 5]


array([0, 0, 0, 0, 0])

In [13]:
print(a2)
np.ones_like(a2) # a2와 같은 shape로 1이 채워진 배열을 만들어줘 /2차원

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [14]:
print(a3)
np.full_like(a3, 10) # a3와 같은 shape로 10으로 채워진 배열을 만들어줘

[[[  1   2   3]
  [  5   6   7]
  [ 43   5  65]]

 [[  1   3   0]
  [ 50  65   7]
  [  3   5  65]]

 [[  1 203   3]
  [556   6   7]
  [  4 556 615]]]


array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

### 생성한 값으로 배열 생성

* `arange()`: 정수 범위로 배열 생성

In [15]:
np.arange(0,30) # 이거는 파이썬에서 range함수와 같다/ 하지만 array로 만들어진다.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

* `linspace()`: 범위 내에서 균등 간격의 배열 생성 

 *로그스케일: 매우 광범위한 범위의 수치 데이터를 로그를 이용하여 간결하게 표시하는 눈금의 일종이다.

In [16]:
np.linspace(0,1,5) # 0부터 1 사이를 출력하는데 균등하게 5등분 해줘

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

* `logspace()`: 범위 내에서 균등간격으로 로그 스케일로 배열 생성

In [17]:
np.logspace(0.1,1,5)

array([ 1.25892541,  2.11348904,  3.54813389,  5.95662144, 10.        ])

### 랜덤값으로 배열 생성


* `random.random()`: 랜덤한 수의 배열 생성

In [18]:
np.random.random() # 기본 랜덤은 실수값을 반환해준다
np.random.random((4,4)) # 이거는 안에 shape을 넣어주는 것이다.

array([[0.66676697, 0.26282174, 0.32772623, 0.52040943],
       [0.70316221, 0.34399963, 0.57527103, 0.78366675],
       [0.2734269 , 0.89159706, 0.89479251, 0.29183417],
       [0.95312178, 0.1250867 , 0.09378926, 0.44254359]])

* `random.randint()`: 일정 구간의 랜덤 정수의 배열 생성

In [19]:
np.random.randint(0,30, (2,3)) # 0부터 30까지 2 by 3 shape

array([[28, 28, 20],
       [24, 22, 22]])

* `random.normal()`: 정규분포(normal distribution)를 고려한 랜덤한 수의 배열 생성
* 평균=0, 표준편차=1, 3 x 3 배열

In [20]:
np.random.normal(0, 34, (3,4)) # 0 부터 34까지 3 by 4 사이즈로 만든 표준편차

array([[ 59.24377068, -30.57438426,  -2.61636036, -11.16482947],
       [ -9.91417675,   0.92036111,  -5.77795509, -41.59858592],
       [-42.79811366,  14.31809607,  19.31801691, -48.80360579]])

* `random.rand()`: 균등분포(uniform distribution)를 고려한 랜덤한 수의 배열 생성

In [21]:
np.random.rand(3,3) 

array([[0.77394888, 0.39281529, 0.08129895],
       [0.84056456, 0.70661478, 0.07712178],
       [0.43056654, 0.3898734 , 0.07466657]])

* `random.randn()`: 표준 정규 분포(standard normal distribution)를 고려한 랜덤한 수의 배열 생성

In [22]:
np.random.randn(3,4)

array([[-0.4162911 , -0.4713342 , -0.17862354, -2.14498045],
       [ 0.03835597,  0.66851437, -0.25098908,  0.17863224],
       [-0.26839558,  0.30960858,  1.81712223,  0.60171249]])

### 표준 데이터 타입

In [23]:
np.zeros(20, dtype=int) #  0으로 20개를 뽑는데, dtype을 int로 해줘

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
np.ones(30,dtype = bool) # bool 타입으로 함, 1은 T 이므로 다 T 이다.

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [25]:
np.full((3,3),2,dtype = float) # 3by 3으로 2라는 정수값을 실수값으로 표현해줘

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

### 날짜/시간 배열 생성


In [26]:
date = np.array('2023-01-01', dtype = np.datetime64) # datetime64 => 날짜 시간을 나타내게 하는 타입이다.
date

array('2023-01-01', dtype='datetime64[D]')

In [27]:
date + np.arange(12) # 현재 날짜에서 12일 앞의 날짜까지 구해서 배열에 넣어줌

array(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
       '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
       '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12'],
      dtype='datetime64[D]')

In [28]:
datetime = np.datetime64('2023-08-10 23:00')
datetime

numpy.datetime64('2023-08-10T23:00')



---



## 배열 조회

### 배열 속성 정보

In [29]:
def array_info(array):
    print(array)
    print('ndim:', array.ndim) # ndim = 차원
    print('shape:', array.shape)
    print('dtype:',array.dtype)
    print('size:', array.size)
    print('itemsize:', array.itemsize) # 하나의 아이템이 가지는 바이트 사이즈
    print('nbytes:', array.nbytes)#byte의 크기가 몇인지 알 수 있다.
    print('strides:', array.strides) # 다음 차원로 넘어갈 때 필요한 바이트 크기

In [30]:
array_info(a1)

[6 2 3 3 5]
ndim: 1
shape: (5,)
dtype: int32
size: 5
itemsize: 4
nbytes: 20
strides: (4,)


In [31]:
array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim: 2
shape: (3, 3)
dtype: int32
size: 9
itemsize: 4
nbytes: 36
strides: (12, 4)


In [32]:
array_info(a3)

[[[  1   2   3]
  [  5   6   7]
  [ 43   5  65]]

 [[  1   3   0]
  [ 50  65   7]
  [  3   5  65]]

 [[  1 203   3]
  [556   6   7]
  [  4 556 615]]]
ndim: 3
shape: (3, 3, 3)
dtype: int32
size: 27
itemsize: 4
nbytes: 108
strides: (36, 12, 4)


### 인덱싱(Indexing)

In [35]:
print(a1)
print(a1[0])
print(a1[-1])

[6 2 3 3 5]
6
5


In [40]:
print(a2)
print(a2[0,1])
print(a2[1,-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
6


In [44]:
print(a3)
print(a3[1,2,2])
print(a3[2,1,2])

[[[  1   2   3]
  [  5   6   7]
  [ 43   5  65]]

 [[  1   3   0]
  [ 50  65   7]
  [  3   5  65]]

 [[  1 203   3]
  [556   6   7]
  [  4 556 615]]]
65
7


### 슬라이싱(Slicing)

* 슬라이싱 구문: `a[start:stop:step]`
* 기본값: start=0, stop=ndim, step=1

In [50]:
print(a1)
print(a1[0:3])
print(a1[0::2])
print(a1[::-1])

[6 2 3 3 5]
[6 2 3]
[6 3 5]
[5 3 3 2 6]


In [63]:
print(a2)
print('--------------')
print(a2[1])
print('--------------')
print(a2[1,:-1])
print('--------------')
print(a2[:,1:]) # 한 마디로 2차원은 행,열 이라고 보면 된다.
print('--------------')
print(a2[::-1,::-1]) # 행 열 모두 역으로 출력 되도록 하기 위함

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------
[4 5 6]
--------------
[4 5]
--------------
[[2 3]
 [5 6]
 [8 9]]
--------------
[[9 8 7]
 [6 5 4]
 [3 2 1]]


### 불리언 인덱싱(Boolean Indexing)

* 배열 각 요소의 선택 여부를 불리언(True or False)로 지정
* True 값인 인덱스의 값만 조회

In [66]:
print(a1)
print('--------------')

bi = [False, True,True,False,True]
print(a1[bi]) # 이렇게 하면 트루인 값들만 출력이 되게 된다.

print('--------------')
bi1 = [True, False,True,False,False]
print(a1[bi])

[6 2 3 3 5]
--------------
[2 3 5]
--------------
[2 3 5]


In [69]:
# 불리언 인덱싱은 자주 쓰인다.
print(a2)
bi = np.random.randint(0,2,(3,3),dtype = bool) # random 인데 int로 해주고, 2차원 array를 3 by 3으로 만들어 주는데 bool타입으로 해줘
print(bi)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ True False False]
 [False False  True]
 [ True  True False]]


### 팬시 인덱싱(Fancy Indedxing)

In [81]:
print(a1)
print('--------------')
print([a1[0],a1[2]])
print('--------------')
ind = [0,2] # 인덱스를 묶어서 한 번에 전달을 해준다. // 위 처럼 각각 적을 필요가 없다.
print(a1[ind])

ind1 = np.array([[0,1],  # 1차원 배열에 2차원 인덱싱을 주면 2차원으로 나온다.
               [2,0]])
print('--------------')

print(a1[ind1])

[6 2 3 3 5]
--------------
[6, 3]
--------------
[6 3]
--------------
[[6 2]
 [3 6]]


In [98]:
print(a2)
# 세로로 한 번 봐보자
row = np.array([0,2]) # 행
col = np.array([1,2]) # 열
print('--------------')
print(a2[row,col]) 
print('--------------')
print(a2[row,:])
print('--------------')
print(a2[:,col])
print('--------------')
print(a2[1:,col])
print('--------------')
print(a2[row,1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------
[2 9]
--------------
[[1 2 3]
 [7 8 9]]
--------------
[[2 3]
 [5 6]
 [8 9]]
--------------
[[5 6]
 [8 9]]
--------------
[[2 3]
 [8 9]]




---



## 배열 값 삽입/수정/삭제/복사

### 배열 값 삽입

* `insert()`: 배열의 특정 위치에 값 삽입
* axis를 지정하지 않으면 1차원 배열로 변환
* 추가할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [105]:
print(a1)

b1 = np.insert(a1,0,10) # np.insert(array, 위치(인덱스), 넣어줄 값 )
print('--------------')
print(b1)
# a1 은 바뀌지 않고, b1이라는 새로운 배열이 생김
print('--------------')
c1 = np.insert(a1,3,44)
print(c1)

[6 2 3 3 5]
--------------
[10  6  2  3  3  5]
--------------
[ 6  2  3 44  3  5]


In [110]:
print(a2)
print('--------------')
b2 = np.insert(a2,1,10,axis = 0) # axis = 0 은 행
c2 = np.insert(a2,1,90,axis =1) # axis =1 은 열이다.
print(b2)
print('--------------')
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
--------------
[[ 1 90  2  3]
 [ 4 90  5  6]
 [ 7 90  8  9]]


### 배열 값 수정

* 배열의 인덱싱으로 접근하여 값 수정

In [119]:
print(a1)
a1[0] = 5
a1[1] = 12
a1[2] = 31
print('--------------')

print(a1)
print('--------------')

a1[:2] =78 # 슬라이싱을 통해서 어느 부분부터 어디까지 바꿔달라는게 가능하다.
print(a1)
print('--------------')

i = np.array([1,3,4]) # 팬시 인덱싱을 통한 방법이다.
a1[i] = 0 
print(a1)
print('--------------')

a1[i] +=4 # a1의 i번째에 4를 더해서 출력하라는 것도 된다.
print(a1)

[78  4 31  4  4]
--------------
[ 5 12 31  4  4]
--------------
[78 78 31  4  4]
--------------
[78  0 31  0  0]
--------------
[78  4 31  4  4]


In [122]:
print(a2) 
a2[0,0] =1
a2[1,1] = 2
a2[2,2] = 3
a2[0] =1 # 0번째 행이 다 1로 바뀜
print('--------------')
print(a2)
print('--------------')
a2[1:,2] = 19
print(a2)

[[1 1 1]
 [4 2 6]
 [7 8 3]]
--------------
[[1 1 1]
 [4 2 6]
 [7 8 3]]
--------------
[[ 1  1  1]
 [ 4  2 19]
 [ 7  8 19]]


### 배열 값 삭제

* `delete()`: 배열의 특정 위치에 값 삭제
* axis를 지정하지 않으면 1차원 배열로 변환
* 삭제할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [123]:
print(a1) # 원본배열은 변경이 되지 않았다.
b1 = np.delete(a1,1) # a1에서 첫 번째 것을 삭제해줘
print('--------------')
print(b1)

[78  4 31  4  4]
--------------
[78 31  4  4]


In [126]:
print(a2)
b2 = np.delete(a2,1,axis = 0)
c2 = np.delete(a2,1,axis = 1)
print('--------------')
print(b2)
print('--------------')
print(c2)

[[ 1  1  1]
 [ 4  2 19]
 [ 7  8 19]]
--------------
[[ 1  1  1]
 [ 7  8 19]]
--------------
[[ 1  1]
 [ 4 19]
 [ 7 19]]


### 배열 복사

* 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님

In [140]:
print(a2)
print('--------------')
print(a2[:2,:2])
print('--------------')
a2_sub = a2[:2,:2]
print(a2_sub)
a2_sub[:,1] = 33
print('--------------')
print(a2_sub)
print('--------------')
print(a2) # 원본 배열도 바뀜 / 카피를 안 붙이면 그대로 원본도 바뀜

[[ 1 33  1]
 [ 4 33 19]
 [ 7  8 19]]
--------------
[[ 1 33]
 [ 4 33]]
--------------
[[ 1 33]
 [ 4 33]]
--------------
[[ 1 33]
 [ 4 33]]
--------------
[[ 1 33  1]
 [ 4 33 19]
 [ 7  8 19]]



* `copy()`: 배열이나 하위 배열 내의 값을 명시적으로 복사

In [144]:
 print(a2)
print('--------------')
a2_sub_copy = a2[:2,:2].copy()
print(a2_sub_copy)
print('--------------')
a2_sub_copy[:,1] =23
print(a2_sub_copy)
print('--------------')
print(a2) # 원본은 23으로 바뀌지 않음

[[ 1 33  1]
 [ 4 33 19]
 [ 7  8 19]]
--------------
[[ 1 33]
 [ 4 33]]
--------------
[[ 1 23]
 [ 4 23]]
--------------
[[ 1 33  1]
 [ 4 33 19]
 [ 7  8 19]]




---



## 배열 변환

### 배열 전치 및 축 변경

In [146]:
print(a2)
print('--------------')
print(a2.T) # 행과 열이 전치가 된다.

[[ 1 33  1]
 [ 4 33 19]
 [ 7  8 19]]
[[ 1  4  7]
 [33 33  8]
 [ 1 19 19]]


In [147]:
print(a3)
print('--------------')
print(a3.T)

[[[  1   2   3]
  [  5   6   7]
  [ 43   5  65]]

 [[  1   3   0]
  [ 50  65   7]
  [  3   5  65]]

 [[  1 203   3]
  [556   6   7]
  [  4 556 615]]]
--------------
[[[  1   1   1]
  [  5  50 556]
  [ 43   3   4]]

 [[  2   3 203]
  [  6  65   6]
  [  5   5 556]]

 [[  3   0   3]
  [  7   7   7]
  [ 65  65 615]]]


In [149]:
print(a2)
print('--------------')
print(a2.swapaxes(1,0)) # Transport와 똑같은 결과물이 만들어진다.

[[ 1 33  1]
 [ 4 33 19]
 [ 7  8 19]]
--------------
[[ 1  4  7]
 [33 33  8]
 [ 1 19 19]]


In [153]:
print(a3)
print('--------------')
print(a3.swapaxes(0,1))
print('--------------')
print(a3.swapaxes(1,2))

[[[  1   2   3]
  [  5   6   7]
  [ 43   5  65]]

 [[  1   3   0]
  [ 50  65   7]
  [  3   5  65]]

 [[  1 203   3]
  [556   6   7]
  [  4 556 615]]]
--------------
[[[  1   2   3]
  [  1   3   0]
  [  1 203   3]]

 [[  5   6   7]
  [ 50  65   7]
  [556   6   7]]

 [[ 43   5  65]
  [  3   5  65]
  [  4 556 615]]]
--------------
[[[  1   5  43]
  [  2   6   5]
  [  3   7  65]]

 [[  1  50   3]
  [  3  65   5]
  [  0   7  65]]

 [[  1 556   4]
  [203   6 556]
  [  3   7 615]]]


### 배열 재구조화


* `reshape()`: 배열의 형상을 변경

In [155]:
n1 = np.arange(1,10)
print(n1)
print('--------------')
print(n1.reshape(3,3)) # 1차원 배열을 2차원으로 바꿈

[1 2 3 4 5 6 7 8 9]
--------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]


* `newaxis()`: 새로운 축 추가

In [156]:
print(n1)
print('--------------') 
print(n1[np.newaxis,:5]) # row로 축 추가
print('--------------')
print(n1[:5,np.newaxis]) # col로 축 추가

[1 2 3 4 5 6 7 8 9]
--------------
[[1 2 3 4 5]]
--------------
[[1]
 [2]
 [3]
 [4]
 [5]]


### 배열 크기 변경

* 배열 모양만 변경

In [158]:
n2 = np.random.randint(0,10,(2,5))
print(n2)
print('--------------')
n2.resize((5,2)) #배열의 모양이 바뀜
print(n2)

[[9 6 3 7 2]
 [2 1 0 0 6]]
--------------
[[9 6]
 [3 7]
 [2 2]
 [1 0]
 [0 6]]


* 배열 크기 증가
* 남은 공간은 0으로 채워짐

In [160]:
n2.resize((5,5))
print(n2) # 나머지 공간은 0으로 채워진다.

[[9 6 3 7 2]
 [2 1 0 0 6]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


* 배열 크기 감소
* 포함되지 않은 값은 삭제됨

In [161]:
n2.resize((3,3))
print(n2)

[[9 6 3]
 [7 2 2]
 [1 0 0]]


### 배열 추가

* `append()`: 배열의 끝에 값 추가

In [164]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
print('--------------')
b2 = np.arange(10,19).reshape(3,3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------
[[10 11 12]
 [13 14 15]
 [16 17 18]]


* axis 지정이 없으면 1차원 배열 형태로 변형되어 결합

In [165]:
c2= np.append(a2,b2)
print(c2)# 2차원 배열이 1차원 배열로 변형이 됨.


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


* axis를 0으로 지정
* shape[0]을 제외한 나머지 shape은 같아야 함

In [166]:
c2= np.append(a2,b2, axis = 0)
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


* axis를 1로 지정
* shape[1]을 제외한 나머지 shape은 같아야 함

In [167]:
c2= np.append(a2,b2, axis = 1)
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


### 배열 연결

* `concatenate()`: 튜플이나 배열의 리스트를 인수로 사용해 배열 연결

In [168]:
a1 = np.array([1,3,5])
b1 = np.array([2,4,6])
np.concatenate([a1,b1])

array([1, 3, 5, 2, 4, 6])

In [172]:
a2 = np.array([[12,3,4],
             [7,5,6]])
np.concatenate([a2,a2], axis = 1)

array([[12,  3,  4, 12,  3,  4],
       [ 7,  5,  6,  7,  5,  6]])

### 배열 분할

* `split()`: 배열 분할

In [174]:
a1 = np.arange(0,10)
print(a1)
b1 ,c1 = np.split(a1,[5])
print('--------------')
print(b1,c1)
b1, c1, d1, e1, f1 = np.split(a1,[2,4,5,8])
print('--------------')
print(b1,c1,d1,e1,f1)

[0 1 2 3 4 5 6 7 8 9]
--------------
[0 1 2 3 4] [5 6 7 8 9]
--------------
[0 1] [2 3] [4] [5 6 7] [8 9]




---



## 배열 연산

* NumPy의 배열 연산은 벡터화(vectorized) 연산을 사용
* 일반적으로 NumPy의 범용 함수(universal functions)를 통해 구현
* 배열 요소에 대한 반복적인 계산을 효율적으로 수행

### 브로드캐스팅(Broadcasting)

In [182]:
a1 = np.array([1,2,3])
print(a1)
print(a1+5)
print('--------------')

a2 = np.arange(1,10).reshape(3,3)
print(a2)
print('--------------')
print(a1+a2)

[1 2 3]
[6 7 8]
--------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


### 산술 연산(Arithmetic Operators)

In [190]:
a1 = np.arange(1,10)
print(a1)
print('--------------') 
print(np.add(a1,10)) # 덧셈
print('--------------')
print(np.subtract(a1,10)) # 마이너스
print('--------------')
print(np.multiply(a1,10)) # 곱셈
print('--------------')
print(np.divide(a1,4)) # 나눗셈

[1 2 3 4 5 6 7 8 9]
--------------
[ 2  3  4  5  6  7  8  9 10]
--------------
[11 12 13 14 15 16 17 18 19]
--------------
[-9 -8 -7 -6 -5 -4 -3 -2 -1]
--------------
[10 20 30 40 50 60 70 80 90]
--------------
[0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   2.25]


### 집계 함수(Aggregate Functions)

#### sum(): 합 계산

In [194]:
a2 = np.random.randint(1,10,size = (3,3))
print(a2)
print('--------------')
print(a2.sum(),np.sum(a2))
print('--------------')
print(a2.sum(axis=0),np.sum(a2,axis = 0))
print('--------------')
print(a2.sum(axis=0),np.sum(a2,axis = 1))

[[2 2 5]
 [2 7 5]
 [8 9 9]]
--------------
49 49
--------------
[12 18 19] [12 18 19]
--------------
[12 18 19] [ 9 14 26]


#### prod(): 곱 계산

In [195]:
print(a2)
print('--------------')
print(np.prod(a2,axis = 0))
print('--------------')
print(np.prod(a2,axis = 1))

[[2 2 5]
 [2 7 5]
 [8 9 9]]
--------------
[ 32 126 225]
--------------
[ 20  70 648]


#### mean(): 평균 계산

In [197]:
print(a2)
print('--------------')
print(np.mean(a2))
print('--------------')
print(np.mean(a2, axis = 0))
print('--------------')
print(np.mean(a2, axis = 1))

[[2 2 5]
 [2 7 5]
 [8 9 9]]
--------------
5.444444444444445
--------------
[4.         6.         6.33333333]
--------------
[3.         4.66666667 8.66666667]


#### min(): 최소값

In [198]:
print(a2)
print('--------------')
print(np.min(a2))
print('--------------')
print(np.min(a2, axis = 0))
print('--------------')
print(np.min(a2, axis = 1))

[[2 2 5]
 [2 7 5]
 [8 9 9]]
--------------
2
--------------
[2 2 5]
--------------
[2 2 8]


#### max(): 최대값

In [ ]:
print(a2)
print('--------------')
print(np.max(a2))
print('--------------')
print(np.max(a2, axis = 0))
print('--------------')
print(np.max(a2, axis = 1))

#### median(): 중앙값

In [199]:
print(a2)
print('--------------')
print(np.median(a2))
print('--------------')
print(np.median(a2, axis = 0))
print('--------------')
print(np.median(a2, axis = 1))

[[2 2 5]
 [2 7 5]
 [8 9 9]]
--------------
5.0
--------------
[2. 7. 5.]
--------------
[2. 5. 9.]


#### percentile(): 백분위 수



In [206]:
a1 = np.array([0,1,2,3])
print(a1)
print('--------------')
print(np.percentile(a1,[0,20,40,60,80,100],interpolation = 'linear'))
print('--------------')
print(np.percentile(a1,[0,20,40,60,80,100],interpolation = 'higher'))
print('--------------')
print(np.percentile(a1,[0,20,40,60,80,100],interpolation = 'lower'))
print('--------------')
print(np.percentile(a1,[0,20,40,60,80,100],interpolation = 'nearest'))
print('--------------')
print(np.percentile(a1,[0,20,40,60,80,100],interpolation = 'midpoint'))


[0 1 2 3]
--------------
[0.  0.6 1.2 1.8 2.4 3. ]
--------------
[0 1 2 2 3 3]
--------------
[0 0 1 1 2 3]
--------------
[0 1 1 2 2 3]
--------------
[0.  0.5 1.5 1.5 2.5 3. ]


C:\Users\user\AppData\Local\Temp\ipykernel_16832\3173656720.py:4: DeprecationWarning: the `interpolation=` argument to percentile was renamed to `method=`, which has additional options.
Users of the modes 'nearest', 'lower', 'higher', or 'midpoint' are encouraged to review the method they used. (Deprecated NumPy 1.22)
  print(np.percentile(a1,[0,20,40,60,80,100],interpolation = 'linear'))
C:\Users\user\AppData\Local\Temp\ipykernel_16832\3173656720.py:6: DeprecationWarning: the `interpolation=` argument to percentile was renamed to `method=`, which has additional options.
Users of the modes 'nearest', 'lower', 'higher', or 'midpoint' are encouraged to review the method they used. (Deprecated NumPy 1.22)
  print(np.percentile(a1,[0,20,40,60,80,100],interpolation = 'higher'))
C:\Users\user\AppData\Local\Temp\ipykernel_16832\3173656720.py:8: DeprecationWarning: the `interpolation=` argument to percentile was renamed to `method=`, which has additional options.
Users of the modes 'nearest', 

#### any()

In [208]:
a2 = np.array([[False,False,False],
             [True,True,True],
             [False,True,False]])
print(a2)
print('--------------') # any 는 이 중 하나라도 트루이면 트루이다.
print(np.any(a2))
print('--------------')
print(np.any(a2, axis = 0))
print('--------------')
print(np.any(a2, axis = 1))

[[False False False]
 [ True  True  True]
 [False  True False]]
--------------
True
--------------
[ True  True  True]
--------------
[False  True  True]


#### all()

In [211]:
a2 = np.array([[False,False,True],
             [True,True,True],
             [False,True,True]])
print(a2)
print('--------------') # all은 전부 트루여야 트루이다.
print(np.all(a2))
print('--------------')
print(np.all(a2, axis = 0))
print('--------------')
print(np.all(a2, axis = 1))

[[False False  True]
 [ True  True  True]
 [False  True  True]]
--------------
False
--------------
[False False  True]
--------------
[False  True False]


### 비교 연산(Comparison Operators)


In [213]:
a1 = np.arange(1,10)
print(a1)
print('--------------')
print(a1==5) # 해당하는 비교연산자의 T/F를 나타냄
print('--------------')
print(a1 != 5)
print('--------------')
print(a1 >=5)
print('--------------')
print(a1<= 5)

[1 2 3 4 5 6 7 8 9]
--------------
[False False False False  True False False False False]
--------------
[ True  True  True  True False  True  True  True  True]
--------------
[False False False False  True  True  True  True  True]
--------------
[ True  True  True  True  True False False False False]


#### 불리언 연산자(Boolean Operators)


In [217]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
print('--------------')
print((a2> 5) & (a2< 8))
print('--------------')
print((a2>) | (a2<8))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------
[[False False False]
 [False False  True]
 [ True False False]]
--------------
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### 배열 정렬

In [219]:
a1 = np.random.randint(1,10,size = 10)
print(a1)
print('--------------')
print(np.sort(a1))
print('--------------')
print(a1)
print('--------------')
print(np.argsort(a1))
print('--------------')
print(a1)

[1 5 8 5 6 2 1 5 8 5]
--------------
[1 1 2 5 5 5 5 6 8 8]
--------------
[1 5 8 5 6 2 1 5 8 5]
--------------
[0 6 5 1 3 7 9 4 2 8]
--------------
[1 5 8 5 6 2 1 5 8 5]


#### 부분 정렬

* `partition()`: 배열에서 k개의 작은 값을 반환

In [221]:
a1 = np.random.randint(1,10,size = 10)
print(a1)
print('--------------')
print(np.partition(a1,3)) # 배열에서 가장 작은 값 k개를 반환시켜줘

[9 8 8 3 3 3 4 2 5 5]
--------------
[2 3 3 3 4 5 5 8 8 9]


## 배열 입출력


In [227]:
a2 = np.random.randint(1,10,size = (5,5))
print(a2)
np.save('a',a2)

[[8 8 7 3 4]
 [9 1 4 6 7]
 [6 5 6 5 3]
 [4 8 4 6 5]
 [4 3 6 5 5]]


In [230]:
b2 = np.random.randint(1,10,size=(5,5))
print(b2)
np.savez('ab',a2,b2)

[[8 9 4 5 5]
 [7 1 2 4 4]
 [4 1 8 8 4]
 [5 5 4 8 8]
 [9 2 3 9 1]]




---

